apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  storageClassName: csi-cinder-high-speed
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce