apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: strapi-postgresql
  name: strapi-postgresql
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: strapi-postgresql
  type: LoadBalancer
status:
  loadBalancer: {}
