apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strapi-postgresql
  name: strapi-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-postgresql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi-postgresql
    spec:
      containers:
      - image: dleurs/strapi-postgres-ovh:0.1.3
        name: strapi-postgres-ovh
        resources: {}
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: HOST
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: PORT
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_SSL
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: DATABASE_SSL
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-postgres-secret
              key: ADMIN_JWT_SECRET
status: {}
